server:
  port: 80
# 热部署开关
spring:
#  devtools:
#    restart:
#      enabled: false
  # 入驻eureka的名称
  application:
    name: cloud-order-service
eureka:
  client:
    # 表示是否将自己注册进eureka
    register-with-eureka: true
    # 是否从eurekaserver 抓取已有的注册信息，单节点无所谓，集群模式必须设置才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      # 集群版
  #      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    # eureka id 显示的名称
    instance-id: order80
    # 访问路径可以显示ip地址
    prefer-ip-address: true